name: Electricity-Trading-API-Integration-Tests

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  DEFAULT_PYTHON_VERSION: '3.11'

jobs:
  run-tests:
    name: Integration tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python:
          - "3.11"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git
        uses: frequenz-floss/gh-action-setup-git@v0.x.x

      - name: Print environment (debug)
        run: env

      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev-pytest]
          pip freeze

      - name: Run the integration tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GRIDPOOL_ID: ${{ secrets.GRIDPOOL_ID }}
        run: |
          pytest -vv integration_tests/
        timeout-minutes: 10


